import { avatarImage } from '~/shared/assets/images/avatars';
import { mrBeastImage } from '~/shared/assets/images/user/mrBeast';

export const burgerSectionData = {
  newCollection: {
    widgetTitle: 'New collection',
    data: [
      {
        id: 1,
        imageUrl: mrBeastImage.burger.newCollection.item1,
        title: 'Nashville Hot Chicken Tender Sandwich',
        price: '35.00$',
      },
      {
        id: 2,
        imageUrl: mrBeastImage.burger.newCollection.item2,
        title: 'Chocolate Chip Cookies',
        price: '20.00$',
      },
      {
        id: 3,
        imageUrl: mrBeastImage.burger.newCollection.item3,
        title: 'Chicken Sandwich Combo',
        price: '40.00$',
      },
      {
        id: 4,
        imageUrl: mrBeastImage.burger.newCollection.item4,
        title: 'Beast Style Fries',
        price: '20.00$',
      },
      {
        id: 5,
        imageUrl: mrBeastImage.burger.newCollection.item5,
        title: 'Beast Style Burger Combo',
        price: '40.00$',
      },
    ],
  },
  gallery: {
    widgetTitle: 'Gallery',
    data: [
      mrBeastImage.burger.gallery.item1,
      mrBeastImage.burger.gallery.item2,
      mrBeastImage.burger.gallery.item3,
      mrBeastImage.burger.gallery.item4,
      mrBeastImage.burger.gallery.item5,
      mrBeastImage.burger.gallery.item6,
      mrBeastImage.burger.gallery.item7,
      mrBeastImage.burger.gallery.item8,
      mrBeastImage.burger.gallery.item9,
    ],
  },
  happyClients: {
    widgetTitle: 'Happy Clients',
    data: [
      {
        id: 1,
        date: '15d',
        viewCount: '26k',
        fullName: 'Anna Kushch',
        image: mrBeastImage.burger.happyClient.item1,
        avatar: avatarImage.annaKushchAvatar,
        likesCount: '12k',
        messagesCount: '54',
        verified: true,
        reposts: '12',
        comment: '',
      },
      {
        id: 2,
        date: 'Feb 12',
        viewCount: '32k',
        fullName: 'Alexa',
        image: mrBeastImage.burger.happyClient.item2,
        avatar: avatarImage.alexaAvatar,
        likesCount: '9k',
        messagesCount: '30',
        verified: true,
        reposts: '40',
        comment: '',
      },
      {
        id: 3,
        date: 'Nov 17',
        viewCount: '34k',
        fullName: 'Dmytro Bondarenko',
        image: mrBeastImage.burger.happyClient.item3,
        avatar: avatarImage.dmytroBondarenkoAvatar,
        likesCount: '12k',
        messagesCount: '32',
        verified: true,
        reposts: '41',
        comment: '',
      },
      {
        id: 4,
        date: 'Nov 19',
        viewCount: '37k',
        fullName: 'Samara',
        image: mrBeastImage.burger.happyClient.item4,
        avatar: avatarImage.samaraAvatar,
        likesCount: '12k',
        messagesCount: '32',
        verified: true,
        reposts: '41',
        comment: '',
      },
      {
        id: 5,
        date: 'Sep 24',
        viewCount: '40k',
        fullName: 'Artem Pivovarov',
        image: mrBeastImage.burger.happyClient.item5,
        avatar: avatarImage.artemPivovarovAvatar,
        likesCount: '16k',
        messagesCount: '17',
        verified: true,
        reposts: '39',
        comment: '',
      },
      {
        id: 6,
        date: 'Sep 02',
        viewCount: '42k',
        fullName: 'Dmytro Bondarenko',
        image: mrBeastImage.burger.happyClient.item6,
        avatar: avatarImage.dmytroBondarenkoAvatar,
        likesCount: '18k',
        messagesCount: '18',
        verified: true,
        reposts: '30',
        comment: '',
      },
    ],
  },
  reviews: {
    widgetTitle: 'Reviews',
    data: [
      {
        id: 1,
        date: '15d',
        rating: 3,
        fullName: 'Anna Kushch',
        avatar: avatarImage.annaKushchAvatar,
        comment: 'Wonderful look. I want one more!!!',
      },
      {
        id: 2,
        date: '3d',
        rating: 2,
        fullName: 'Alexa',
        avatar: avatarImage.alexaAvatar,
        comment:
          'This merch is top-tier! The design is clean, the material feels high-quality, and it’s super comfortable to wear. Definitely worth it!',
      },
      {
        id: 3,
        date: '4d',
        rating: 2,
        fullName: 'Dmytro Bondarenko',
        avatar: avatarImage.dmytroBondarenkoAvatar,
        comment:
          'Not bad, but I expected a bit more for the price. The design is cool, but the material could be thicker for a premium feel.',
      },
      {
        id: 4,
        date: '5d',
        rating: 4,
        fullName: 'Samara',
        avatar: avatarImage.samaraAvatar,
        comment:
          'Honestly impressed! The print stays vibrant even after multiple washes, and the fabric is soft. A must-have for any fan!',
      },
      {
        id: 5,
        date: '5d',
        rating: 5,
        fullName: 'Artem Pivovarov',
        avatar: avatarImage.artemPivovarovAvatar,
        comment:
          'Love the creativity behind this merch! It really captures the brand’s vibe, but I wish there were more color options to choose from.',
      },
    ],
  },
};
