import { avatarImage } from '~/shared/assets/images/avatars';
import { communityImage } from '~/shared/assets/images/community';

const communityPageData = {
  pageTitle: 'UI/UX Designers Ukraine',
  breadcrumbs: [
    'Designers Global',
    'UI/UX Designers Global',
    'UI/UX Designers Ukraine',
  ],
  menu: {
    first: [
      'General',
      'News',
      'Courses',
      'Skills',
      'Levels',
      'Jobs',
      'Forum',
      'Boards',
      'Cases',
      'Calendar',
      'Rules',
      'Alterlands',
      'Salary Info',
    ],
  },
  salaryBenchmark: {
    widgetTitle: 'Salary benchmark',
    data: [
      {
        id: '1',
        title: 'Average salary worldwide',
        rate: {
          direction: 'increase' as const,
          value: '12.85%',
          postfix: 'past year',
        },
        amount: '73,509',
        imageUrl: communityImage.salaryBenchmark.graph1,
      },
      {
        id: '2',
        title: 'Average salary in your country',
        rate: {
          direction: 'increase' as const,
          value: '6.12%',
          postfix: 'last month',
        },
        amount: '500',
        imageUrl: communityImage.salaryBenchmark.graph2,
      },
    ],
  },
  news: [
    {
      id: 2,
      avatar: avatarImage.mediumAvatar,
      fullName: 'Medium',
      verified: true,
      date: '18h',
      viewCount: '6k',
      title: 'UX & UI Design for Accessible Modern News App',
      likesCount: '3k',
      messagesCount: '248',
      reposts: '962',
    },
    {
      id: 3,
      avatar: avatarImage.wiredAvatar,
      fullName: 'Wired',
      verified: true,
      date: '18h',
      viewCount: '8k',
      title: 'Google Assistant Finally Gets a Generative AI Glow-Up',
      likesCount: '4k',
      messagesCount: '3k',
      reposts: '2k',
    },
    {
      id: 3,
      avatar: avatarImage.uxPubAvatar,
      fullName: 'UX Pub',
      verified: true,
      date: '18h',
      viewCount: '8k',
      title: 'Pantone has chosen the color of the year 2025',
      likesCount: '4k',
      messagesCount: '3k',
      reposts: '2k',
    },
  ],
  memes: {
    widgetTitle: 'Memes',
    data: [
      {
        id: 1,
        avatar: avatarImage.oleksandrShevchenkoAvatar,
        fullName: 'Oleksandr Shevchenko',
        date: 'Jul 7',
        viewCount: '31k',
        image: communityImage.meme.meme1,
        size: 'large' as const,
        likesCount: '60',
        messagesCount: '15',
        reposts: '88',
      },
      {
        id: 2,
        avatar: avatarImage.dmytroBondarenkoAvatar,
        fullName: 'Dmytro Bondarenko',
        date: 'Jul 7',
        viewCount: '31k',
        image: communityImage.meme.meme2,
        size: 'large' as const,
        likesCount: '12',
        messagesCount: '99',
        reposts: '12',
      },
      {
        id: 3,
        avatar: avatarImage.ivanSydorenkoAvatar,
        fullName: 'Ivan Sydorenko',
        date: 'Jul 7',
        viewCount: '31k',
        image: communityImage.meme.meme3,
        size: 'large' as const,
        likesCount: '13',
        messagesCount: '99',
        reposts: '12',
      },
      {
        id: 4,
        avatar: avatarImage.maksymLevchenkoAvatar,
        fullName: 'Maksym Levchenko',
        date: 'Jul 5',
        viewCount: '31k',
        image: communityImage.meme.meme4,
        size: 'large' as const,
        likesCount: '10',
        messagesCount: '90',
        reposts: '10',
      },
      {
        id: 5,
        avatar: avatarImage.oleksandrShevchenkoAvatar,
        fullName: 'Oleksandr Shevchenko',
        date: 'Jul 7',
        viewCount: '31k',
        image: communityImage.meme.meme5,
        size: 'large' as const,
        likesCount: '60',
        messagesCount: '15',
        reposts: '88',
      },
      {
        id: 6,
        avatar: avatarImage.dmytroBondarenkoAvatar,
        fullName: 'Dmytro Bondarenko',
        date: 'Jul 7',
        viewCount: '31k',
        image: communityImage.meme.meme6,
        size: 'large' as const,
        likesCount: '12',
        messagesCount: '99',
        reposts: '12',
      },
    ],
  },
  forum: {
    widgetTitle: 'Forum',
    data: [
      {
        id: 1,
        avatar: avatarImage.annaKushchAvatar,
        fullName: 'Anna Kushch',
        verified: true,
        date: '12h',
        viewCount: '20k',
        title: "Why designers don't think about good user experience",
        likesCount: '16k',
        messagesCount: '523',
        reposts: '2k',
      },
      {
        id: 2,
        avatar: avatarImage.alexaAvatar,
        fullName: 'Alexa Green',
        verified: true,
        date: '18h',
        viewCount: '6k',
        title: 'There are more designers than was 5 years before, why???',
        likesCount: '3k',
        messagesCount: '248',
        reposts: '962',
      },
      {
        id: 3,
        avatar: avatarImage.artemPivovarovAvatar,
        fullName: 'Artem Pivovarov',
        verified: true,
        date: '18h',
        viewCount: '8k',
        title: 'What is better good ux and bad ui or bad ui and good ux?',
        likesCount: '4k',
        messagesCount: '3k',
        reposts: '2k',
      },
    ],
  },
  banner: {
    widgetTitle: 'Google Internship Opportunity',
    data: {
      imageSrc: communityImage.banner,
    },
  },
  courses: {
    widgetTitle: 'Courses',
    data: [
      {
        id: 1,
        creatorTier: 'Pro' as const,
        creatorName: 'Daniel Scott',
        imageSrc: communityImage.course.course1,
        title: 'Adobe Illustrator CC – Advanced Training Course',
        labels: [
          'Adobe Illustrator',
          'Design Tools',
          'Photo & Video Editing Tools',
          'Graphic Design',
        ],
        price: '0.00$',
        examPrice: '$100',
      },
      {
        id: 2,
        creatorTier: 'E' as const,
        creatorName: 'Alan Ayoubi',
        imageSrc: communityImage.course.course2,
        title: 'Adobe Illustrator Mega Course - From Beginner to Advanced',
        labels: [
          'Adobe Illustrator',
          'Graphic Design',
          'Photo & Video Editing Tools',
          'Graphic Design',
        ],
        price: '0.00$',
        examPrice: '$100',
      },
      {
        id: 3,
        creatorTier: 'Pro' as const,
        creatorName: 'Vako Shvili',
        imageSrc: communityImage.course.course3,
        title: 'Complete Web Design: from Figma to Webflow',
        labels: [
          'Web Design',
          'Web & Mobile Design',
          'UX & Web & Mobile Design',
        ],
        price: '0.00$',
        examPrice: '$100',
      },
      {
        id: 4,
        creatorTier: 'GE' as const,
        creatorName: 'Ray Dombroski',
        imageSrc: communityImage.course.course4,
        title: 'Typographic Logos: Typography and Lettering for Logo Design',
        labels: ['Logo Design', 'Design Tools', 'Photo & Video Editing Tools'],
        price: '0.00$',
        examPrice: '$80',
      },
    ],
  },
};

export { communityPageData };
