import { avatarImage } from '~/shared/assets/images/avatars';
import { f1Image } from '~/shared/assets/images/f1';

const f1PageData = {
  upcomingRaces: {
    widgetTitle: 'Upcoming races',
    data: [
      {
        id: 1,
        days: '21-23',
        month: 'Feb',
        title: 'Testing',
        flagImage: f1Image.upcomingRace.flag1,
        description: 'Formula 1 Aramco pre-season testing 2024',
        trackImage: f1Image.upcomingRace.track1,
      },
      {
        id: 2,
        days: '29-02',
        month: 'Feb-Mar',
        title: 'Round 1',
        flagImage: f1Image.upcomingRace.flag2,
        description: 'Formula 1 Gulf air Bahrain grand prix 2024',
        trackImage: f1Image.upcomingRace.track1,
      },
      {
        id: 3,
        days: '07-09',
        month: 'Mar',
        title: 'Round 2',
        flagImage: f1Image.upcomingRace.flag3,
        description: 'Formula 1 Heineken Australian grand prix 2024',
        trackImage: f1Image.upcomingRace.track2,
      },
    ],
  },
  leaderboards: {
    widgetTitle: 'Leaderboards',
    data: [
      {
        id: 1,
        position: 1,
        name: 'Max Verstappen',
        photo: f1Image.leaderboard.driver1,
        countryFlag: f1Image.leaderboard.flag1,
        points: 393,
      },
      {
        id: 1,
        position: 2,
        name: 'Charles Leclerc',
        photo: f1Image.leaderboard.driver2,
        countryFlag: f1Image.leaderboard.flag2,
        points: 331,
      },
      {
        id: 1,
        position: 3,
        name: 'Lando Norris',
        photo: f1Image.leaderboard.driver3,
        countryFlag: f1Image.leaderboard.flag3,
        points: 307,
      },
    ],
  },
  teamLeaderboards: {
    widgetTitle: 'Team leaderboard',
    data: [
      {
        id: 1,
        position: 1,
        logo: f1Image.teamLeaderboard.teamLogo1,
        name: 'McLaren',
        points: 593,
      },
      {
        id: 2,
        position: 2,
        logo: f1Image.teamLeaderboard.teamLogo2,
        name: 'Ferrari',
        points: 557,
      },
      {
        id: 3,
        position: 3,
        logo: f1Image.teamLeaderboard.teamLogo3,
        name: 'Red Bull',
        points: 554,
      },
    ],
  },
  chat: {
    widgetTitle: 'Chat',
    data: [
      {
        id: 1,
        avatar: avatarImage.maksymLevchenkoAvatar,
        fullName: 'Maksym',
        date: '2m',
        message: 'Haha, every race weekend is the highlight of my life',
        likesCount: '24',
        reposts: '0',
      },
      {
        id: 2,
        avatar: avatarImage.alexaAvatar,
        fullName: 'Andrew',
        date: '4m',
        message:
          'Kamala Harris is an inspiring trailblazer, embodying strength, intelligence, and resilience as the first woman, first Black, and first South Asian Vice President of the United States. Her ability to break barriers and champion justice is truly uplifting, giving hope to future generations. She radiates determination and warmth, proving that bold leadership and compassion can coexist beautifully.',
        likesCount: '30',
        reposts: '0',
      },
      {
        id: 3,
        avatar: avatarImage.danielMooreAvatar,
        fullName: 'Daniel Moore',
        date: '24m',
        message: 'Who believes? What are you saying?',
        likesCount: '32k',
        reposts: '2k',
      },
      {
        id: 4,
        avatar: avatarImage.danielMooreAvatar,
        fullName: 'Daniel Moore',
        date: '42m',
        message:
          "We don’t believe. Politicians need to remember they're here to serve the people, not their own interests. We're tired of the constant games and empty promises!",
        likesCount: '32k',
        reposts: '2k',
      },
    ],
  },
  discussion: {
    widgetTitle: 'Discussion',
    data: [
      {
        id: 1,
        avatar: avatarImage.kamilaAvatar,
        fullName: 'Lina Weis',
        verified: true,
        date: '12h',
        viewCount: '20k',
        title:
          'The strategy call during that pit stop completely changed the race!',
        likesCount: '16k',
        messagesCount: '523',
        reposts: '2k',
        answers: [
          {
            id: 1,
            avatar: avatarImage.landoAvatar,
            fullName: 'Tom Harris',
            verified: true,
            date: '11h',
            viewCount: '12k',
            message: 'They drive faster into the pits than I do on the highway',
            likesCount: '10k',
            reposts: '8k',
            label: {
              text: 'most funny',
              color: 'yellow' as const,
            },
          },
          {
            id: 2,
            avatar: avatarImage.alexaAvatar,
            fullName: 'Jack Gold',
            verified: true,
            date: '10h',
            viewCount: '12k',
            message:
              "it's a thrilling blend of speed, skill, and cutting-edge technology",
            likesCount: '10k',
            reposts: '6k',
            label: {
              text: 'most likes',
              color: 'orange' as const,
            },
          },
        ],
      },
      {
        id: 2,
        avatar: avatarImage.alexaAvatar,
        fullName: 'Alexa Green',
        verified: true,
        date: '18h',
        viewCount: '6k',
        title: 'Did you see how close the cars were during that overtake?',
        likesCount: '3k',
        messagesCount: '248',
        reposts: '962',
        answers: [
          {
            id: 1,
            avatar: avatarImage.cameronAvatar,
            fullName: 'Cameron Williamson',
            verified: true,
            date: '11h',
            viewCount: '12k',
            message:
              'Their reaction time is so fast, I bet they dodge raindrops too!',
            likesCount: '10k',
            reposts: '1k',
            label: {
              text: 'most likes',
              color: 'orange' as const,
            },
          },
          {
            id: 2,
            avatar: avatarImage.cheeAvatar,
            fullName: 'Chee Chok',
            verified: true,
            date: '10h',
            viewCount: '12k',
            message: 'They survived that crash? Unreal!',
            likesCount: '17k',
            reposts: '6k',
            label: {
              text: 'most shocked',
              color: 'green' as const,
            },
          },
        ],
      },
    ],
  },
  posts: {
    widgetTitle: 'PROs',
    data: [
      {
        id: 1,
        date: 'Jul 5',
        viewCount: '91k',
        fullName: 'Lando Norris',
        text: ['😈😈😈😈😈'],
        image: f1Image.post.post1,
        avatar: avatarImage.landoAvatar,
        likesCount: '32k',
        messagesCount: '523',
        reposts: '1.2k',
      },
      {
        id: 2,
        date: 'Jul 7',
        viewCount: '84k',
        fullName: 'Lando Norris',
        text: [
          'My tribute to a hero of mine 🇧🇷',
          "Senna is a true legend of our sport and has inspired not only me but every driver who races today. He's the greatest to ever race around Monaco and I wanted to capture that in this helmet. His iconic design combined with mirrored chrome to reflect the streets he was so great on.",
        ],
        image: f1Image.post.post2,
        avatar: avatarImage.landoAvatar,
        likesCount: '42k',
        messagesCount: '872',
        reposts: '2.1k',
      },
      {
        id: 3,
        date: 'Jul 10',
        viewCount: '910k',
        fullName: 'Lando Norris',
        text: ['The first crunch of tayto cheese and onion crisps'],
        image: f1Image.post.post3,
        avatar: avatarImage.landoAvatar,
        likesCount: '310k',
        messagesCount: '2k',
        reposts: '3.6k',
      },
    ],
  },
  memes: {
    widgetTitle: 'Memes',
    data: [
      {
        id: 1,
        avatar: avatarImage.kamilaAvatar,
        fullName: 'Kamila Crown',
        date: 'Jul 7',
        viewCount: '31k',
        image: f1Image.meme.meme1,
        size: 'small' as const,
        likesCount: '60',
        messagesCount: '15',
        reposts: '88',
      },
      {
        id: 2,
        avatar: avatarImage.landoAvatar,
        fullName: 'Lando Norris',
        date: 'Jul 7',
        viewCount: '31k',
        image: f1Image.meme.meme2,
        size: 'small' as const,
        likesCount: '12',
        messagesCount: '99',
        reposts: '12',
      },
      {
        id: 3,
        avatar: avatarImage.cheeAvatar,
        fullName: 'Chee Chok',
        date: 'Jul 7',
        viewCount: '31k',
        image: f1Image.meme.meme3,
        size: 'medium' as const,
        likesCount: '13',
        messagesCount: '99',
        reposts: '12',
      },
      {
        id: 4,
        avatar: avatarImage.alexaAvatar,
        fullName: 'Alexa Green',
        date: 'Jul 5',
        viewCount: '31k',
        image: f1Image.meme.meme4,
        size: 'medium' as const,
        likesCount: '10',
        messagesCount: '90',
        reposts: '10',
      },
      {
        id: 5,
        avatar: avatarImage.samaraAvatar,
        fullName: 'Samara Tompson',
        date: '5h',
        viewCount: '12k',
        image: f1Image.meme.meme5,
        size: 'large' as const,
        likesCount: '11',
        messagesCount: '45',
        reposts: '9',
      },
    ],
  },
  news: {
    widgetTitle: 'News',
    data: [
      {
        id: 1,
        avatar: avatarImage.skySportsAvatar,
        date: '12h',
        viewCount: '91k',
        fullName: 'Sky Sports',
        title:
          'F1 news, rumours and gossip: Formula 1 latest updates on teams, driver transfer market and contracts',
        likesCount: '32k',
        messagesCount: '523',
        reposts: '1.2k',
      },
      {
        id: 2,
        avatar: avatarImage.f1Avatar,
        date: '12h',
        viewCount: '91k',
        fullName: 'Formula 1',
        title:
          'Formula 1 comes to life in brick form as full LEGO range unveiled',
        likesCount: '3k',
        messagesCount: '2k',
        reposts: '406',
      },
      {
        id: 3,
        avatar: avatarImage.f1Avatar,
        date: '12h',
        viewCount: '91k',
        fullName: 'Formula 1',
        title:
          'What time is the Formula 1 2024 Las Vegas Grand Prix and how can I watch it?',
        likesCount: '2k',
        messagesCount: '1k',
        reposts: '750',
      },
    ],
  },
  videos: {
    widgetTitle: 'Videos',
    data: [
      {
        id: 1,
        avatar: avatarImage.f1Avatar,
        date: '12h',
        viewCount: '91k',
        fullName: 'Formula 1',
        videoSrc: 'https://www.youtube.com/embed/LyPxiCgy-Xo',
        title:
          "Final Q3 lap 'a nightmare' - Leclerc unhappy with his Vegas Qualifying performance",
        likesCount: '32k',
        messagesCount: '523',
        reposts: '1.2k',
      },
      {
        id: 2,
        avatar: avatarImage.landoAvatar,
        date: '12h',
        viewCount: '91k',
        fullName: 'Lando Norris',
        videoSrc: 'https://www.youtube.com/embed/dDMplXKlz6E',
        title: 'Qualifying Highlights: 2024 Las Vegas Grand Prix',
        likesCount: '32k',
        messagesCount: '523',
        reposts: '1.2k',
      },
      {
        id: 3,
        avatar: avatarImage.landoAvatar,
        date: '12h',
        viewCount: '91k',
        fullName: 'Lando Norris',
        videoSrc: 'https://www.youtube.com/embed/LXuTH26m11c',
        title: 'NO WAY EDDIE JORDAN SAID THIS ABOUT OSCAR PIASTRI! F1 News',
        likesCount: '32k',
        messagesCount: '523',
        reposts: '1.2k',
      },
    ],
  },
  merch: {
    widgetTitle: 'Merch',
    data: [
      {
        id: 1,
        imageUrl: f1Image.merch.item1,
        title: 'Formula 1 Neon Nights Gradient Foundation Jersey',
        price: '91.00$',
      },
      {
        id: 2,
        imageUrl: f1Image.merch.item2,
        title: 'Formula 1 Neon Nights Gradient Foundation Jersey',
        price: '100.00$',
      },
      {
        id: 3,
        imageUrl: f1Image.merch.item3,
        title: 'Formula 1 Neon Nights Gradient Foundation Jersey',
        price: '105.00$',
      },
      {
        id: 4,
        imageUrl: f1Image.merch.item4,
        title: 'Formula 1 Neon Nights Gradient Foundation Jersey',
        price: '76.00$',
      },
      {
        id: 5,
        imageUrl: f1Image.merch.item5,
        title: 'Formula 1 Neon Nights Gradient Foundation Jersey',
        price: '81.00$',
      },
      {
        id: 6,
        imageUrl: f1Image.merch.item6,
        title: 'Formula 1 Neon Nights Gradient Foundation Jersey',
        price: '140.00$',
      },
    ],
  },
};

export { f1PageData };
