import { avatarImage } from '~/shared/assets/images/avatars';
import { mrBeastImage } from '~/shared/assets/images/user/mrBeast';

export const storeSectionData = [
  {
    id: 1,
    date: '15d',
    viewCount: '26k',
    fullName: 'Anna Kushch',
    image: mrBeastImage.happyClient.item1,
    avatar: avatarImage.annaKushchAvatar,
    likesCount: '12k',
    messagesCount: '54',
    verified: true,
    reposts: '12',
    comment:
      "Senna is a true legend of our sport and has inspired not only me but every driver who races today. He's the greatest to ever race around Monaco and I wanted to capture that in this helmet.",
  },
  {
    id: 2,
    date: 'Feb 12',
    viewCount: '32k',
    fullName: 'Alexa',
    image: mrBeastImage.happyClient.item2,
    avatar: avatarImage.alexaAvatar,
    likesCount: '9k',
    messagesCount: '30',
    verified: true,
    reposts: '40',
    comment: '',
  },
  {
    id: 3,
    date: 'Nov 17',
    viewCount: '34k',
    fullName: 'Dmytro Bondarenko',
    image: mrBeastImage.happyClient.item3,
    avatar: avatarImage.dmytroBondarenkoAvatar,
    likesCount: '12k',
    messagesCount: '32',
    verified: true,
    reposts: '41',
    comment: '',
  },
  {
    id: 4,
    date: 'Nov 19',
    viewCount: '37k',
    fullName: 'Samara',
    image: mrBeastImage.happyClient.item4,
    avatar: avatarImage.samaraAvatar,
    likesCount: '12k',
    messagesCount: '32',
    verified: true,
    reposts: '41',
    comment: '',
  },
  {
    id: 5,
    date: 'Sep 24',
    viewCount: '40k',
    fullName: 'Artem Pivovarov',
    image: mrBeastImage.happyClient.item5,
    avatar: avatarImage.artemPivovarovAvatar,
    likesCount: '16k',
    messagesCount: '17',
    verified: true,
    reposts: '39',
    comment: '',
  },
  {
    id: 6,
    date: 'Sep 02',
    viewCount: '42k',
    fullName: 'Dmytro Bondarenko',
    image: mrBeastImage.happyClient.item6,
    avatar: avatarImage.dmytroBondarenkoAvatar,
    likesCount: '18k',
    messagesCount: '18',
    verified: true,
    reposts: '30',
    comment: '',
  },
];
